-- Tạo Databas

CREATE DATABASE QL_Kho_CHDAN

GO

-- Sử dụng Database vừa tạo
USE QL_Kho_CHDAN
GO

-- Tạo các bảng cùng khoá chính
CREATE TABLE MatHang
(
	MaHang INT IDENTITY(1,1),
	TenHang NVARCHAR(500),
	DvTinh NVARCHAR(500),
	DonGia DECIMAL(12,3) DEFAULT 0,
	MaLoai TINYINT,

	CONSTRAINT PK_MatHang PRIMARY KEY(MaHang)
)
GO

CREATE TABLE LoaiHang
(
	MaLoai TINYINT IDENTITY(1,1),
	TenLoai NVARCHAR(50),

	CONSTRAINT PK_LoaiHang PRIMARY KEY(MaLoai)
)
GO

ALTER TABLE LoaiHang
ADD CONSTRAINT C_lOAIHANG_TENLOAI	CHECK (TenLoai IN (N'món ăn', N'đồ uống', N'nguyên liệu chế biến', N'dụng cụ', N'nhiên liệu'))
GO

CREATE TABLE CungUng
(
	MaHang INT NOT NULL,
	MaNCC INT NOT NULL,
	GiaCungUng DECIMAL(12,3) DEFAULT 0,
	NgayCapNhatGia DATE DEFAULT GETDATE(),
	DangNhap BIT,

	CONSTRAINT PK_CungUng PRIMARY KEY(MaHang,MaNCC)
)
GO

CREATE TABLE LoHang
(
	MaLo INT IDENTITY(1,1),	
	HSD DATE,
	TonKho INT DEFAULT 0,
	MaHang INT,
	MaDPN INT,

	CONSTRAINT PK_LoHang PRIMARY KEY(MaLo)
)
GO

CREATE TABLE NhaCungCap
(
	MaNCC INT IDENTITY(1,1),
	TenNCC NVARCHAR(500)

	CONSTRAINT PK_NhaCungCap PRIMARY KEY(MaNCC)
)
GO

CREATE TABLE NhanVien
(
	MaNV TINYINT IDENTITY(1,1),
	TenNV NVARCHAR(60),
	GioiTinh BIT,
	NgaySinh DATE,
	SDT CHAR(11),
	CaLam NTEXT,
	Luong DECIMAL(12,3) DEFAULT 0,
	MaNguoiQL TINYINT,

	CONSTRAINT PK_NhanVien PRIMARY KEY(MaNV)
)
GO

CREATE TABLE PhieuNhap
(
	MaPhieuNhap INT IDENTITY(1,1) NOT NULL,
	ThoiGian DATETIME DEFAULT GETDATE(),
	MaNV TINYINT,
	MaNCC INT,
	NoPN DECIMAL(16,3) DEFAULT 0, -- Nợ
	TongTien DECIMAL(16,3) DEFAULT 0,

	CONSTRAINT PK_PhieuNhap PRIMARY KEY(MaPhieuNhap)
)
GO

CREATE TABLE PhieuXuat
(
	MaPhieuXuat INT IDENTITY(1,1),
	ThoiGian DATETIME DEFAULT GETDATE(),
	MaNV TINYINT,
	TenNguoiNhan NVARCHAR(60),
	DiaChiKho NVARCHAR(500),
	TongTien DECIMAL(16,3) DEFAULT 0,

	CONSTRAINT PK_PhieuXuat PRIMARY KEY(MaPhieuXuat)
)
GO

CREATE TABLE DongPhieuNhap
(
	MaDPN INT IDENTITY(1,1),
	MaPhieuNhap INT,	
	SoLuong INT DEFAULT 0,
	DonGiaNhap DECIMAL(10,3) DEFAULT 0,

	CONSTRAINT PK_DongPhieuNhap PRIMARY KEY(MaDPN)
)
GO

CREATE TABLE DongPhieuXuat
(
	MaLo INT,
	MaPhieuXuat INT,
	SoLuong INT  DEFAULT 0,

	CONSTRAINT PK_DongPhieuXuat PRIMARY KEY(MaLo,MaPhieuXuat)
)
GO

-- Tạo các khoá ngoại
ALTER TABLE dbo.MatHang ADD CONSTRAINT FK_MatHang_MaLoai FOREIGN KEY(MaLoai) REFERENCES dbo.LoaiHang(MaLoai)
GO

ALTER TABLE dbo.CungUng ADD CONSTRAINT FK_CungUng_MaNCC FOREIGN KEY(MaNCC) REFERENCES dbo.NhaCungCap(MaNCC)
GO

ALTER TABLE dbo.CungUng ADD CONSTRAINT FK_CungUng_MaHang FOREIGN KEY(MaHang) REFERENCES dbo.MatHang(MaHang)
GO

ALTER TABLE dbo.LoHang ADD CONSTRAINT FK_LoHang_MaHang FOREIGN KEY(MaHang) REFERENCES dbo.MatHang(MaHang)
GO

ALTER TABLE dbo.LoHang ADD CONSTRAINT FK_LoHang_DongPhieuNhap FOREIGN KEY(MaDPN) REFERENCES dbo.DongPhieuNhap(MaDPN)
GO

ALTER TABLE dbo.DongPhieuNhap ADD CONSTRAINT FK_DongPhieuNhap_MaPhieuNhap FOREIGN KEY(MaPhieuNhap) REFERENCES dbo.PhieuNhap(MaPhieuNhap)
GO

ALTER TABLE dbo.DongPhieuXuat ADD CONSTRAINT FK_DongPhieuXuat_MaLo FOREIGN KEY(MaLo) REFERENCES dbo.LoHang(MaLo)
GO

ALTER TABLE dbo.DongPhieuXuat ADD CONSTRAINT FK_DongPhieuXuat_MaPhieuXuat FOREIGN KEY(MaPhieuXuat) REFERENCES dbo.PhieuXuat(MaPhieuXuat)
GO

ALTER TABLE dbo.PhieuNhap ADD CONSTRAINT FK_PhieuNhap_MaNV FOREIGN KEY(MaNV) REFERENCES dbo.NhanVien(MaNV)
GO

ALTER TABLE dbo.PhieuNhap ADD CONSTRAINT FK_PhieuNhap_MaNCC FOREIGN KEY(MaNCC) REFERENCES dbo.NhaCungCap(MaNCC)
GO

ALTER TABLE dbo.PhieuXuat ADD CONSTRAINT FK_PhieuXuat_MaNV FOREIGN KEY(MaNV) REFERENCES dbo.NhanVien(MaNV)
GO

ALTER TABLE dbo.NhanVien ADD CONSTRAINT FK_NhanVien_MaNguoiQL FOREIGN KEY(MaNguoiQL) REFERENCES dbo.NhanVien(MaNV)
GO